### ISSUE TITLE
DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by insignedesign** [spiratype/balancer#1]
Hello, I have installed the balancer module per the instructions. However, I get the following in the python console: 

Traceback (most recent call last):
  File "<string>", line 5, in <module>
ImportError: DLL load failed: The specified module could not be found.

balancer_core.pyd is present and there is a brief pause as I assume it loads the compiled file. I have other working pyd files for RMX tools.

I am on windows 10 with python 2.7.16 32 bit. FL 5.2.2 32 bit. I have also installed cython. No effect.

Thank you,

**Comment by spiratype** [comment]
I apologize for the late response. 

The problem lies in the compile-time linking which I have so far been unable to rectify using newer versions of [MinGW/GCC](http://winlibs.com). The version just released (0.1.4) is compiled with an older version of MinGW/GCC ([4.3.3](https://github.com/develersrl/gccwinbinaries)) and works on a separate PC with a fresh install of Windows 10 and FontLab Studio 5.2.

**Comment by insignedesign** [comment]
It works! Fantastic. Thanks for fixing this.
